language: go
sudo: false
go:
  - 1.9.3
addons:
  apt:
    packages:
      rpm
install:
  - gem install fpm
script:
  - make travis_test
  - make rpm
after_success:
  - bash <(curl -s https://codecov.io/bash)
